### ISSUE TITLE
xmr mining?

### ISSUE THREAD

**Issue by sherifomran** [Lopo/NiceHashQtMiner#1]
is it possible to mine monero or similar cryptonight coins with it in an idle modus ?
can i cooperate on it.

**Comment by Lopo** [comment]
Theoretically, yes, but now I have no time for further development of this project. I primarily work on things I have at least some money for.
In addition, I have started a completely new version that will be more modular and versatile, without Qt or similar FW. But again, there is the problem with time and money for living.

**Comment by sherifomran** [comment]
yes, i know this problem and happens to me very often, i am willing to cooperate with you on it.
coordinate the duties with me and we can do it together. What will the programming language be?

**Comment by Lopo** [comment]
It's C++17 ... but for now I don't have time for it, and I will release it when could be used at least partially
