### ISSUE TITLE
unable to open with qt creator under mac

### ISSUE THREAD

**Issue by sherifomran** [Lopo/NiceHashQtMiner#3]
Running "/usr/local/bin/cmake -E server --pipe=/tmp/cmake-.FTlUYJ/socket --experimental" in /Users/sherifomran/Desktop/build-NiceHashQtMiner-master-Desktop_Qt_5_12_1_CLang-Default.
Starting to parse CMake project, using: "-DCMAKE_CXX_COMPILER:STRING=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++", "-DCMAKE_C_COMPILER:STRING=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang", "-DCMAKE_PREFIX_PATH:STRING=/Users/sherifomran/Qt5.12.1/5.12.1/clang_64", "-DQT_QMAKE_EXECUTABLE:STRING=/Users/sherifomran/Qt5.12.1/5.12.1/clang_64/bin/qmake".
Running CMake version 3.14.5
The C compiler identification is AppleClang 10.0.0.10001145
The CXX compiler identification is AppleClang 10.0.0.10001145
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang
Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Detecting C compile features
Detecting C compile features - done
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++
Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
CUDA_TOOLKIT_ROOT_DIR set to /opt/cuda
Performing Test COMPILER_KNOWS_CXX11
Performing Test COMPILER_KNOWS_CXX11 - Success
Performing Test COMPILER_KNOWS_STDLIB
Performing Test COMPILER_KNOWS_STDLIB - Success
Looking for pthread.h
Looking for pthread.h - found
Looking for pthread_create
Looking for pthread_create - found
Found Threads: TRUE  
Boost version: 1.56.0
Found the following Boost libraries:
  filesystem
  thread
  system
  chrono
  date_time
  atomic
Performing Test CXX_COMPILER_WALL
Performing Test CXX_COMPILER_WALL - Success
Performing Test CXX_COMPILER_WEXTRA
Performing Test CXX_COMPILER_WEXTRA - Success
Performing Test CXX_COMPILER_WNOUNUSEDPARAMETER
Performing Test CXX_COMPILER_WNOUNUSEDPARAMETER - Success
Looking for stdint.h
Looking for stdint.h - found
Looking for pthread_create in pthreads
Looking for pthread_create in pthreads - not found
Looking for pthread_create in pthread
Looking for pthread_create in pthread - found
OPENCL_INCLUDE_DIRS: /System/Library/Frameworks/OpenCL.framework
Looking for CL_VERSION_2_0
Looking for CL_VERSION_2_0 - not found
Looking for CL_VERSION_1_2
Looking for CL_VERSION_1_2 - found
Looking for CL_VERSION_1_1
Looking for CL_VERSION_1_1 - found
FindOpenCL searching for 64-bit libraries
Found OPENCL: /System/Library/Frameworks/OpenCL.framework (found version "1.2") 
FindOpenCL /System/Library/Frameworks/OpenCL.framework, /System/Library/Frameworks/OpenCL.framework
** AMD Display Library (ADL) root directory .....: 
** AMD Display Library (ADL) library directory...: ADL_LIBRARY_DIR-NOTFOUND
** AMD Display Library (ADL) library.............: /Users/sherifomran/Desktop/NiceHashQtMiner-master/lib/libatiadlxx.so
** AMD Display Library (ADL) library works.......: FALSE
Could NOT find ADL (missing: ADL_INCLUDE_DIR) 
Could NOT find CUDA (missing: CUDA_NVCC_EXECUTABLE CUDA_INCLUDE_DIRS CUDA_CUDART_LIBRARY) (Required is at least version "8.0")
** NVIDIA Display Library (NVML) root directory .....: 
** NVIDIA Display Library (NVML) library.............: NOT FOUND
If your have an NVIDIA GPU, please install NVIDIA Device Drivers!
Otherwise, you should configure BOSP to DISABLE NVIDIA Power Management
Could NOT find NVML (missing: NVML_INCLUDE_DIR) 
Could NOT find NVML (missing: NVML_LIBRARY) 
Looking for cpuid_present in cpuid
Looking for cpuid_present in cpuid - not found
Looking for hd_list in hd
Looking for hd_list in hd - not found
Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
Checking for module 'xscrnsaver'
  No package 'xscrnsaver' found
Creating /Users/sherifomran/Desktop/NiceHashQtMiner-master/include/version.h
NiceHashQtMiner 0.1.2-dev

Platform: Other/No platform code
System  : Darwin-17.7.0
	Arch: x86_64
	compiler  | AppleClang 10.0.0.10001145
	cxxflags  |  -std=c++11 -stdlib=libc++
	builddir  | /Users/sherifomran/Desktop/build-NiceHashQtMiner-master-Desktop_Qt_5_12_1_CLang-Default
	buildtype | Debug
Building with support for:
  Debug:                yes
  	- SWITCH_TESTING:    no
  AMD:                  yes
  	- OPENCL:            yes
  	- ADL:               
  		- FOUND:            no
  		- LIBWORKS:         no
  NVIDIA:               no
  	- CUDA:              no
  	- NVML:              no
  SCRNSAVER:            no
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
LOG4_LIBRARY
    linked by target "NiceHashQtMiner" in directory /Users/sherifomran/Desktop/NiceHashQtMiner-master/NiceHashQtMiner

Configuring incomplete, errors occurred!
See also "/Users/sherifomran/Desktop/build-NiceHashQtMiner-master-Desktop_Qt_5_12_1_CLang-Default/CMakeFiles/CMakeOutput.log".
See also "/Users/sherifomran/Desktop/build-NiceHashQtMiner-master-Desktop_Qt_5_12_1_CLang-Default/CMakeFiles/CMakeError.log".
CMake Project parsing failed.

**Comment by Lopo** [comment]
1/ This project is not counted to work on Mac ... but it is not excluded
2/ CMake clearly writes what's wrong: "Please set them or make sure they are set and tested correctly in the CMake files: LOG4_LIBRARY" - you have to install Log4Qt lib
3/ maybe some other libs/pkgs are needed to install (cpuid, libhd-dev/hwinfo, ...)

but all of that doesn't guarantee, that it will work on Mac - I do not own it nor have access to any
